<a href="https://colab.research.google.com/github/ugurcankuzu/Sentimental-Analysis-ML/blob/main/LogisticRegressionModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import numpy as np
import pandas as pd
import re

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

import nltk
from nltk import word_tokenize

!pip install pickle5
import pickle5 as pk
nltk.download('stopwords')
nltk.download('punkt')

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pickle5 in /usr/local/lib/python3.8/dist-packages (0.0.11)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [31]:
trainData = pd.read_csv("/content/twitter_training.csv",header=None)
trainData

,0,1,2,3
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
...,...,...,...,...
74677,9200,Nvidia,Positive,Just realized that the Windows partition of my...
74678,9200,Nvidia,Positive,Just realized that my Mac window partition is ...
74679,9200,Nvidia,Positive,Just realized the windows partition of my Mac ...
74680,9200,Nvidia,Positive,Just realized between the windows partition of...
74681,9200,Nvidia,Positive,Just like the windows partition of my Mac is l...

In [32]:
trainData.columns = ["id","takenFrom","type","text"]
trainData

,id,takenFrom,type,text
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
...,...,...,...,...
74677,9200,Nvidia,Positive,Just realized that the Windows partition of my...
74678,9200,Nvidia,Positive,Just realized that my Mac window partition is ...
74679,9200,Nvidia,Positive,Just realized the windows partition of my Mac ...
74680,9200,Nvidia,Positive,Just realized between the windows partition of...
74681,9200,Nvidia,Positive,Just like the windows partition of my Mac is l...

In [33]:
trainDup = trainData

In [34]:
#Text Format Section

trainDup["lower"] = trainDup.text.str.lower() #Text lowercase convert
trainDup["lower"] = [str(data) for data in trainDup.lower] #Text string convert
trainDup["lower"] = trainDup.lower.apply(lambda x: re.sub('[^A-Za-z0-9 ]+', ' ', x)) #Text filtering using RegEx

trainDup

,id,takenFrom,type,text,lower
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...,im getting on borderlands and i will murder yo...
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...,i am coming to the borders and i will kill you...
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...,im getting on borderlands and i will kill you ...
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...,im coming on borderlands and i will murder you...
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...,im getting on borderlands 2 and i will murder ...
...,...,...,...,...,...
74677,9200,Nvidia,Positive,Just realized that the Windows partition of my...,just realized that the windows partition of my...
74678,9200,Nvidia,Positive,Just realized that my Mac window partition is ...,just realized that my mac window partition is ...
74679,9200,Nvidia,Positive,Just realized the windows partition of my Mac ...,just realized the windows partition of my mac ...
74680,9200,Nvidia,Positive,Just realized between the windows partition of...,just realized between the windows partition of...
74681,9200,Nvidia,Positive,Just like the windows partition of my Mac is l...,just like the windows partition of my mac is l...

In [35]:
#Text Split Section
textToken = [word_tokenize(str(word)) for word in trainDup.lower]

tokenCount = [item for text in textToken for item in text]

print("Token Count is : {}".format(len(set(tokenCount))))

Token Count is : 30436

In [36]:
#Ineffective words in english for model

stopWords = nltk.corpus.stopwords.words('english')
stopWords[:10] #Example

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]

In [37]:
#Vectorizing Texts

vectorizer = CountVectorizer(
    tokenizer = word_tokenize,
    stop_words = stopWords,
    ngram_range = (1,1)
)

In [38]:
#Split Dataset

Xtrain,Xtest = train_test_split(trainDup,test_size=0.2,shuffle=True)

In [49]:
XtrainVector = vectorizer.fit_transform(Xtrain.lower)
XtestVector = vectorizer.transform(Xtest.lower)

In [50]:
YtrainVector = Xtrain.type
YtestVector = Xtest.type

In [51]:
XtestVector.shape

(14937, 29017)

In [48]:
Xtest

,id,takenFrom,type,text,lower
48779,5973,HomeDepot,Negative,@GovLauraKelly ordinance mandate masks in publ...,govlaurakelly ordinance mandate masks in publ...
18900,12439,WorldOfCraft,Positive,Excited to get back into @Warcraft today! Afte...,excited to get back into warcraft today afte...
31514,7411,LeagueOfLegends,Positive,This is pretty fun guy to watch if any of you ...,this is pretty fun guy to watch if any of you ...
24627,4627,Google,Neutral,@sandramyers2252 The Scam Shield app is here! ...,sandramyers2252 the scam shield app is here ...
36771,8308,Microsoft,Positive,Here's what I've came back to! Put dispenser h...,here s what i ve came back to put dispenser h...
...,...,...,...,...,...
30685,7272,LeagueOfLegends,Negative,My dopamine receptors have been fucked by the ...,my dopamine receptors have been fucked by the ...
25941,852,AssassinsCreed,Neutral,Via game_kik. â€¢ â€¢ â€¢ â€¢ â€¢ â€¢. Assassins Creed Val...,via game kik assassins creed valh...
6061,243,Amazon,Neutral,"With ""Everyday Victory In Jesus"" you will cert...",with everyday victory in jesus you will cert...
27167,1074,AssassinsCreed,Irrelevant,Excellent! I look forward to Vinland starting ...,excellent i look forward to vinland starting ...
19467,12533,WorldOfCraft,Neutral,I always get sad in the troll starter area whe...,i always get sad in the troll starter area whe...

In [53]:
latestModel = None
for i in np.arange(0.1,1.0,0.1):
  accuracy = 0
  model = LogisticRegression(C=i,solver="liblinear",max_iter=200)
  model.fit(XtrainVector,YtrainVector)
  prediction = model.predict(XtestVector)
  calc = accuracy_score(YtestVector,prediction)*100

  print("For C value: {}Accuracy Value: {}".format(i,calc))
  if(calc > accuracy):
    accuracy = calc
    latestModel = model

For C value: 0.1Accuracy Value: 72.5045189797148
For C value: 0.2Accuracy Value: 76.22012452299658

/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

For C value: 0.30000000000000004Accuracy Value: 76.75570730401017

/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

For C value: 0.4Accuracy Value: 78.1080538260695

/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

For C value: 0.5Accuracy Value: 79.16582981857132
For C value: 0.6Accuracy Value: 81.97763941889268
For C value: 0.7000000000000001Accuracy Value: 82.46635870656759
For C value: 0.8Accuracy Value: 82.9082145009038
For C value: 0.9Accuracy Value: 83.329985940952

In [57]:
with open("model.pickle","wb") as f:
  pk.dump(latestModel,f)